project:
  type: website
  output-dir: docs

website:
  title: "Learning Cyber Security - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cloud-security.qmd
      - web-security.qmd
      - on-premise-systems-and-networks-security.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
